name: learning cron expression
on:
  schedule:
    - cron: '* *  * * *'

jobs:
 cron_job:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - name: run cron job
         run: echo 'Running cron job..........'
          