name: Push docker image to AWS ECR

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        # outputs:
        #     my_output: ${{ steps.set_output.outputs.myvalue}}
        # steps:
        #     - name: Set Output value
        #       id: set_output
        #       run: echo "::set-output name=my_value::Hello world"
        steps:
          - uses: actions/checkout@v4  #cloning the code
          - name: Set up JDK 11 for x64 #installing jdk (java)
            uses: actions/setup-java@v4
            with:
               java-version: '11'
               distribution: 'temurin'
               architecture: x64
               cache: maven
          - name: Build with maven
            run: |
               cd java-maven-build
               mvn -B package --file pom.xml
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                 aws-region: ap-south-1
                 
       
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1

          - name: Build, tag, and push the image to Amazon ECR
            id: build-image
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              
              IMAGE_TAG: ${{ github.sha }}
            run: |
              cd java-maven-build
              docker build -t $ECR_REGISTRY/github_actions:$IMAGE_TAG .
              docker push $ECR_REGISTRY/github_actions:$IMAGE_TAG