name: java app with maven

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4  #cloning the code
          - name: Set up JDK 11 for x64 #installing jdk (java)
            uses: actions/setup-java@v4
            with:
               java-version: '11'
               distribution: 'temurin'
               architecture: x64
               cache: maven
          - name: Build with maven
            run: |
               cd java-maven-build
               mvn -B package --file pom.xml
               echo $GITHUB_WORKSPACE
               ls
               cd target
               ls
               mkdir staging && cp target/*.jar staging
               
          - uses: actions/upload-artifact@v4
            with:
                name: package
                path: java-maven-build/staging