name: learning secrets

on: [workflow_dispatch]

env:
    NODE_ENV: 'development'
jobs:
    secrets:
        runs-on: ubuntu-latest
        environment: testing
        steps:
            - name: fetching env vars
              run: |
                 echo "My devops environment is $NODE_ENV"
                 echo "Username is ${{ secrets.DB_USERNAME}}"
                 echo 'Password is ${{ secrets.DB_PWD}}'
                 echo 'My env is ${{ env.NODE_ENV }}'
                 echo "My env is $NODE_ENV"
        