name: learning secrets

on: [workflow_dispatch]


jobs:
    secrets:
        runs-on: ubuntu-latest
        
        steps:
            - name: fetching env vars
              run: |
                 echo "My devops environment is $NODE_ENV"
                 echo "Username is ${{ secrets.DB_USERNAME}}"
                 echo 'Password is ${{ secrets.DB_PWD}}'