name: self hosted runner


on : [workflow_dispatch]    # [push]--> for auto trigger

jobs:
   test:
        runs-on: node1
        steps:
        - uses: actions/checkout@v4
        - name: Print Workspace path
          run: |
              python test.py