name: workflow for user input

on: 
    workflow_dispatch:
        inputs:
          environment:
            description: "Env to Deploy"
            required: true
            default: 'production'
            type: choice
            options:
                - prod
                - qa
                - dev
          notify:
            description: "Notify the  Deployment status"
            required: true
            default: 'true'
            type: choice
            options:
                - true
                - false
                

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying to ${{ github.event.inputs.environment}} environment" 
    notify:
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs.notify}}
        steps:
            - run: "Deployed to ${{ github.event.inputs.environment}} environment"
            