name: learning passing the variables

on: [workflow_dispatch]


jobs:
    first_job:
        runs-on: ubuntu-latest
        outputs:
            my_output: ${{ steps.step2.outputs.my_output}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate output
              id: step1
              run: echo "my_value" > output.txt
            - name: set output
              id: step2
              run: echo "::set-output name=my_output::$(cat output.txt)"
    second_job:
        runs-on: ubuntu-latest
        needs: first_job
        steps:
            - name: Use the previous step output
              run: echo "The output from prev job is ${{ needs.first_job.outputs.my_output}}"
            